site_name: DEVSE - Wiki
site_description: Documentation de DEVSE
repo_url: https://github.com/DEV-SE-FR/documentation-dev-se-fr
theme:
  name: material
  language: fr
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github
  features:
    - instant

markdown_extensions:
  - markdown.extensions.meta
  - pymdownx.highlight
  - pymdownx.inlinehilite