site_name: DEVSE - Wiki
copyright: Creative Commons Attribution 2.0 France
site_description: Documentation de DEVSE
repo_url: https://github.com/DEV-SE-FR/documentation-dev-se-fr
theme:
  name: material
  language: fr
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github
  features:
    - instant

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JnKQsXm

markdown_extensions:
  - markdown.extensions.meta
  - pymdownx.highlight
  - pymdownx.inlinehilite