site_name: DEVSE - Wiki
copyright: Creative Commons Attribution 2.0 France
site_description: Documentation de DEVSE
repo_url: https://github.com/DEV-SE-FR/documentation-dev-se-fr
theme:
  name: material
  language: fr
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github
  features:
    - instant

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/3XjkM6q

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.keys

extra_javascript:
  - javascripts/highlight.pack.js
  - javascripts/config.js
extra_css:
  - styles/syntax.css
