site_name: DEVSE - Wiki
copyright: Creative Commons Attribution 2.0 France
site_description: Documentation de DEVSE
repo_url: https://github.com/DEV-SE-FR/documentation-dev-se-fr
theme:
  name: material
